title: cloudlad.io
author: Nikola Velkovski
email: nvelkovski@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Having fun in the cloud.

markdown: kramdown
# social links
twitter_username: kikolanikola
github_username:  parabolic
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: nikola-velkovski-231ba824
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-sitemap

exclude:
  - CNAME
  - docker-compose.yml
  - docker_env
  - docker_logo.png
  - Dockerfile
  - jekyll_logo.png
  - README.md
  - Gemfile*
