title: cloudlad.io
author: Nikola
email: nikola@cloudlad.io
description: > # this means to ignore newlines until "twitter_username:"
  Technologist /
  Certified Kubernetes Administrator /
  Terraform Assosiate /
  Hashicorp ambassador (2020/2021)

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  skin: solarized-dark
  social_links:
    github:  parabolic

google_analytics: UA-137373669-1

markdown: kramdown

kramdown:
  input: GFM

# Pagination
paginate: 3
paginate_path: /page:num/

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - CNAME
  - docker-compose.yml
  - docker_env
  - docker_logo.png
  - Dockerfile
  - jekyll_logo.png
  - README.md
  - Gemfile*
