version: "3"
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - .:/app
    environment:
      - JEKYLL_ENV=docker

    command: jekyll serve --host 0.0.0.0 --port 5000 --watch --incremental --trace --disable-disk-cache
    ports:
      - 5000:5000
